name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Use Deno 1.x
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Lint (Biome)
        run: pnpm run lint:biome
        env:
          CI: true

      - name: Lint (TypeScript)
        run: pnpm run lint:ts
        env:
          CI: true

      - name: Test (Node.js)
        run: pnpm run test:node
        env:
          CI: true

      - name: Send coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info

      - name: Test (Deno)
        run: pnpm run test:deno
        env:
          CI: true

      - name: Test (Bun)
        run: pnpm run test:bun
        env:
          CI: true

      - name: Build
        run: pnpm run build:ts
        env:
          CI: true

      - name: Build (docs)
        run: pnpm run build:docs
        env:
          CI: true
